=== OleksandrDudkin/Semester2/out/production/Semester2/Practica1_XML/group.dtd
<!-- <!ELEMENT название элемента (что может содержать)> корневой элемент group содержит элементы student
* — ноль или много. ? – ноль или один. + — один или много. если знак не указан, то элемент только один -->

<!ELEMENT group (student*)>
<!ELEMENT student (subject*,average?)>      <!-- элемент student cодержит ноль или больше предметов, ноль или одну запись о среднем балле -->
<!ATTLIST student firstname CDATA #REQUIRED lastname CDATA #REQUIRED groupnumber CDATA #REQUIRED>
                <!-- перечисляются аттрибуты student -->
                <!-- CDATA указывает, что разбирать содержимое атрибутов не нужно  -->
                <!-- #REQUIRED - элемент обязательный -->

<!ELEMENT subject EMPTY>            <!-- элемент subject должен быть пустым(содержит только атрибуты)   -->
<!ATTLIST subject title CDATA #REQUIRED mark (1|2|3|4|5) #REQUIRED>  <!-- в скобках перечисляем обязательные значения атрибута mark.  -->
<!ELEMENT average (#PCDATA)>        <!-- #PCDATA - анализатор обязан разбирать содержимое элемента  -->

=== OleksandrDudkin/Semester2/out/production/Semester2/Practica1_XML/group.xml
<?xml version = "1.0"?>
<!DOCTYPE group SYSTEM "group.dtd">
<!-- если сразу подключить файл dtd, то подсветяться красным все отклонения -->

<group>
    <student firstname="Ivan" lastname="Ivanchenko" groupnumber="A-1">
        <subject title="Math" mark="5"/>
        <subject title="Chemistry" mark="4"/>
        <subject title="Physics" mark="3"/>
        <subject title="Geometry" mark="4"/>
        <average>4.0</average>
    </student>
    <student firstname="Petr" lastname="Petrenko" groupnumber="A-1">
        <subject title="Math" mark="3"/>
        <subject title="Chemistry" mark="3"/>
        <subject title="Physics" mark="3"/>
        <subject title="Geometry" mark="4"/>
        <average>7.5</average>
    </student>
    <student firstname="Mykola" lastname="Mykolayenko" groupnumber="A-1">
        <subject title="Math" mark="5"/>
        <subject title="Chemistry" mark="3"/>
        <subject title="Physics" mark="5"/>
        <subject title="Geometry" mark="5"/>
        <average>4.75</average>
    </student>
    <student firstname="Sydor" lastname="Sydorenko" groupnumber="A-1">
        <subject title="Math" mark="5"/>
        <subject title="Chemistry" mark="4"/>
        <subject title="Physics" mark="3"/>
        <subject title="Geometry" mark="5"/>
        <average>7</average>
    </student>
</group>
